#' Estimate optimal SI for a single voltration
#'
#' @param SI Dataframe with at least the following columns:
#'           Group, Pctg_OutOfRange, rSD, SI.
#'           For example as part of the object generated by estimate_brightness.
#'
#' @returns The same object, in which an additional column "Optimal"
#'          is added in the SI dataframe, which will have one TRUE value per
#'          group
#' @export
indicate_optimal_voltages <- function(SI){
  SI$Optimal <- FALSE
  for(group in unique(SI$Group)){
    subset <- which(SI$Group == group)
    opt <- indicate_optimal_voltages_single(SI[subset,])
    SI$Optimal[subset] <- opt
  }
  return(SI)
}

#' Estimate optimal SI for a single voltration
#'
#' @param SI Dataframe with at least the following columns:
#'           Pctg_OutOfRange, rSD, SI.
#'           For example as part of the object generated by estimate_brightness.
#'
#' @returns vector with 1 for optimal value, 0 for suboptimal values and NA
#'          for rows which were not considered due to too many cells out of
#'          range or too large rSD
#' @export
indicate_optimal_voltages_single <- function(SI,
                                             max_outOfRange = 0.01,
                                             max_rSD = 3){
  optimal <- rep(NA, nrow(SI))
  min_rSD <- SI[which.min(SI$Voltage), "rSD"]
  considered <- SI[,"Pctg_OutOfRange"] <= max_outOfRange &
    SI[,"rSD"] <= max_rSD * min_rSD
  optimal[considered] <- 0
  optimal[considered][which.max(SI[considered, "SI"])] <- 1

  return(optimal)
}
